### ISSUE TITLE
[ Question - Récupération liste d'éléments dans factory ]

### ISSUE THREAD

**Issue by DavidRion** [Testatoo/testatoo#103]
Bonjour,

Est il possible de récupérer une liste de composants via testatoo ?
Par exemple, une liste de Link ayant une classe spécifique, un peu comme ci-dessous :

```
List<Link> getElements() {
     $(".maClasse") as List<A>
}
```

Pour l'instant et en lisant la doc, j'arrive seulement à récupérer un élément spécifique à la fois.

Merci d'avance,

**Comment by altus34** [comment]
Oui comme cela (avec le double $)

* List<A> elements = $$('.maClasse', A)
