### ISSUE TITLE
[ Question - type Key ENTER ]

### ISSUE THREAD

**Issue by DavidRion** [Testatoo/testatoo#104]
Bonjour,

Est il possible de simuler la touche Entrée via Testatoo ?

Il y a pas mal de touches proposées dans la classe Key, mais pas celle-ci.
Je n'arrive pas à la simuler en JQuery via un runscript.

Merci,

**Comment by altus34** [comment]
Key.RETURN devrait repondre a tes besoins.

**Comment by DavidRion** [comment]
Super! Merci!
